sequenceDiagram
    autonumber
    participant C as Client
    participant PS as Google Cloud<br>Pub/Sub
    participant ISS as InitializeSurveySubscriber<br>.net core
    participant FS as Google Cloud<br>Firestore
    C->>+PS: INITIALIZE_SURVEY
    PS-->>C: response
    PS--)ISS: INITIALIZE_SURVEY
    deactivate PS
    activate ISS
    %% SAVE_SURVEY
    ISS->>+PS: SAVE_SURVEY
    PS-->>ISS: response
    deactivate PS
    %% SAVE_SURVEY_STATUS
    ISS->>+PS: SAVE_SURVEY_STATUS
    PS-->>ISS: response
    deactivate PS
    %% SAVE_SURVEY_RESULT
    loop for each participant
        ISS->>+PS: SAVE_SURVEY_RESULT
        PS-->>ISS: response
        deactivate PS
    end
    %% CREATE_MAIL
    ISS->>+PS: CREATE_MAIL
    PS-->>ISS: response
    deactivate PS
    deactivate ISS