name: BE/EvaluateSurveyService.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'backend/EvaluateSurveyService/**'
  workflow_dispatch:
env:
  FUNCTION_NAME: EvaluateSurveyService
  ENTRY_POINT: on_evaluate_survey  
  SOURCE_DIR: 'backend/EvaluateSurveyService'
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: EvaluateSurveyService-Test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: python39
          entry_point: ${{ env.ENTRY_POINT }}
          project_id: ${{ secrets.PROJECT_ID }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/${{ secrets.TOPIC_NAME_EVALUATE_SURVEY }}
          source_dir: ${{ env.SOURCE_DIR }}
          env_vars: ENV_IS_PRODUCTION=${{ secrets.IS_PRODUCTION }},ENV_COLLECTION_NAME=${{ secrets.COLLECTION_NAME }},ENV_SURVEY_VIEWER_LINK=${{ secrets.SURVEY_VIEWER_LINK }},ENV_PROJECT_ID=${{ secrets.PROJECT_ID }},ENV_TOPIC_NAME_SEND_MAIL=${{ secrets.TOPIC_NAME_SEND_MAIL }}
