name: SaveSurveyResultSubscriber
on:
  push:
    branches:
      - main
    paths:
      'backend/SaveSurveyResultSubscriber/**'
  workflow_dispatch:
  workflow_run:
    workflows: [SaveSurveyResultSchema]
    types: [completed]
jobs:
  BuildAndDeploy:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-deploy-google-cloud-function.yaml@main
    with:
      functionName: SaveSurveyResultSubscriber 
      projectName: SaveSurveyResultSubscriber
      solutionFolder: backend/SaveSurveyResultSubscriber
      trigger: pubsub
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      appSettingsJsonTest: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_TEST }}\",\"Environment\": \"Test\",\"EvaluateSurveyTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_EVALUATE_SURVEY }}\",\"CreateMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_MAIL }}\"\}'
      appSettingsJsonStage: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_STAGE }}\",\"Environment\": \"Stage\",\"EvaluateSurveyTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_EVALUATE_SURVEY }}\",\"CreateMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_MAIL }}\"\}'
      appSettingsJsonProd: '\{\"Logging\":\{\"LogLevel\":\{\"Microsoft\":\"Error\"\}\},\"ProjectId\": \"${{ secrets.GLOBAL_PROJECT_ID_PROD }}\",\"Environment\": \"Prod\",\"EvaluateSurveyTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_EVALUATE_SURVEY }}\",\"CreateMailTopicName\": \"${{ secrets.GLOBAL_PUBSUB_TOPIC_CREATE_MAIL }}\"\}'
      subTopicName: ${{ secrets.GLOBAL_PUBSUB_TOPIC_SAVE_SURVEY_RESULT }}
