name: schemas/Schema.SaveSurvey.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'schemas/SaveSurveySchema.avro'
      - '.github/workflows/Schema.SaveSurvey.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/deploy-google-cloud-pubsub-schema-topic.yaml@main
    with:
      messageEnconding: json
      schemaFile: schemas/SaveSurveySchema.avro
      schemaType: AVRO
    secrets:
      gcpCredentialsTest: ${{ secrets.GLOBAL_GCP_CREDENTIALS_TEST }}
      gcpCredentialsStage: ${{ secrets.GLOBAL_GCP_CREDENTIALS_STAGE }}
      gcpCredentialsProd: ${{ secrets.GLOBAL_GCP_CREDENTIALS_PROD }}
      projectIdTest: ${{ secrets.GLOBAL_PROJECT_ID_TEST }}
      projectIdStage: ${{ secrets.GLOBAL_PROJECT_ID_STAGE }}
      projectIdProd: ${{ secrets.GLOBAL_PROJECT_ID_PROD }}
      topicName: ${{ secrets.GLOBAL_SAVE_SURVEY_SERVICE_SUB }}