name: nugets/Surveys.Common.PubSub.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'nugets/Surveys.Common.PubSub/Surveys.Common.PubSub/**'
  workflow_dispatch:
env:
  CONFIG: Release
  CSPROJ_FILE: 'nugets/Surveys.Common.PubSub/Surveys.Common.PubSub/Surveys.Common.PubSub.csproj'
  PACKAGE_FILE_BASE: 'nugets/Surveys.Common.PubSub/Surveys.Common.PubSub/bin'
  PACKAGE_SOURCE: 'https://nuget.pkg.github.com/MichaelDiers'
  PACKAGE_VERSION: '1.0.$GITHUB_RUN_NUMBER'
  SLN_FILE: 'nugets/Surveys.Common.PubSub/Surveys.Common.PubSub.sln'
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}"
      - name: test
        run: dotnet test ${{ env.SLN_FILE }} --configuration "${{ env.CONFIG }}" --no-build
      - name: pack
        run: dotnet pack "${{ env.CSPROJ_FILE }}" -c "${{ env.CONFIG }}" -p:PackageVersion=${{ env.PACKAGE_VERSION }} --no-build
      - name: publish
        run: dotnet nuget push "${{ env.PACKAGE_FILE_BASE }}/${{ env.CONFIG }}/*.nupkg" --source ${{ env.PACKAGE_SOURCE }} --api-key ${{ env.NUGET_AUTH_TOKEN }} --skip-duplicate --no-symbols true