name: nugets/Surveys.Common.Firestore.yaml
on:
  push:
    branches:
      - main
    paths:
      - 'nugets/Surveys.Common.Firestore/**'
      - '.github/workflows/Surveys.Common.Firestore.yaml'
  workflow_dispatch:
jobs:
  createSchemaAndTopic:
    uses: MichaelDiers/shared-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      projectName: Surveys.Common.Firestore
      solutionFolder: nugets/Surveys.Common.Firestore
    secrets:
      nugetAuthToken: ${{ secrets.NUGET_AUTH_TOKEN }}
