//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateMailSubscriber.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThankYou {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThankYou() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateMailSubscriber.Logic.ThankYou", typeof(ThankYou).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;h1&gt;Hej {0}!&lt;/h1&gt;&lt;p&gt;Vielen Dank für Teilnahme an der Umfrage &lt;a href=&apos;{2}&apos;&gt;{1}&lt;/a&gt;!&lt;/p&gt;&lt;p&gt;{4}&lt;/p&gt;&lt;p&gt;Viele Grüße,&lt;br&gt;&lt;br&gt;{3}&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string BodyHtml {
            get {
                return ResourceManager.GetString("BodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} {1}&lt;/li&gt;.
        /// </summary>
        public static string BodyHtmlResult {
            get {
                return ResourceManager.GetString("BodyHtmlResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Deine gewählten Antworten&lt;/h2&gt;&lt;ol&gt;{0}&lt;/ol&gt;.
        /// </summary>
        public static string BodyHtmlResultList {
            get {
                return ResourceManager.GetString("BodyHtmlResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej {0},
        ///
        ///vielen Dank für Deine Teilnahme an der Umfrage &apos;{1}&apos;.
        ///
        ///{4}
        ///Der Link zur Umfrage:
        ///
        ///{2}
        ///
        ///Viele Grüße,
        ///
        ///{3}.
        /// </summary>
        public static string BodyText {
            get {
                return ResourceManager.GetString("BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - {0} {1}
        ///.
        /// </summary>
        public static string BodyTextResult {
            get {
                return ResourceManager.GetString("BodyTextResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine gewählten Antworten:
        ///
        ///{0}.
        /// </summary>
        public static string BodyTextResultList {
            get {
                return ResourceManager.GetString("BodyTextResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für Deine Stimme in der Umfrage {0}.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
    }
}
